import { expect, test } from '@playwright/test'
import { resetDemo } from './helpers/demo'

test.beforeEach(async ({ page }) => resetDemo(page))

test('opens the latest project tree as the application home', async ({ page }) => {
  await page.goto('/')

  await expect(page).toHaveURL('/project/project-demo-family/tree')
  await expect(page.getByRole('navigation', { name: '项目导航' })).toBeVisible()
  await expect(page.getByText('中心人物：林海')).toBeVisible()

  await page.getByRole('link', { name: '项目管理', exact: true }).click()
  await expect(page.locator('.app-topbar')).toBeVisible()
  await expect(page.getByRole('button', { name: '刷新资料' })).toHaveCount(0)
  const projectOverview = page.locator('.project-overview')
  await expect(projectOverview.getByRole('link', { name: '新建项目', exact: true })).toBeVisible()
  await projectOverview.getByRole('link', { name: '新建项目', exact: true }).click()
  await expect(page).toHaveURL('/project/project-demo-family/manage/new')
  await expect(page.getByRole('link', { name: '项目管理', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '数据检查', exact: true })).toBeVisible()
  await expect(page.locator('.app-topbar')).toBeVisible()
  await expect(page.locator('.app-topbar').getByRole('link', { name: '返回项目管理' })).toBeVisible()
  await expect(page.getByRole('button', { name: '刷新资料' })).toHaveCount(0)

  await page.getByRole('link', { name: '返回当前项目家谱树' }).click()
  await expect(page).toHaveURL('/project/project-demo-family/tree')
})

for (const viewport of [{ width: 1280, height: 900 }, { width: 390, height: 844 }]) {
  test(`GitHub import keeps one accessible header back button at ${viewport.width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport)
    await page.goto('/new')

    await page.getByRole('link', { name: '从 GitHub 导入已有项目' }).click()

    await expect(page).toHaveURL('/github-import')
    await expect(page.getByRole('heading', { name: '从 GitHub 导入' })).toBeVisible()
    await expect(page.getByText('GitHub 项目导入仅在桌面端可用')).toBeVisible()
    const header = page.locator('.home-layout__header')
    const back = header.getByRole('button', { name: '返回上一页' })
    await expect(back).toBeVisible()
    await expect(page.locator('.page-back-link')).toHaveCount(1)
    await expect(page.getByRole('link', { name: '返回首页' })).toHaveCount(0)
    await expect(header.getByRole('link', { name: 'Branchloom 首页' })).toHaveCount(0)
    await expect(header.getByRole('link', { name: '从 GitHub 导入项目' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: '刷新资料' })).toHaveCount(0)
    await expect(page.locator('.github-import-view__intro .icon-tabler-brand-github')).toHaveCount(0)
    expect(await page.locator('html').evaluate((element) => element.scrollWidth))
      .toBeLessThanOrEqual(viewport.width)

    await back.focus()
    await page.keyboard.press('Tab')
    await page.keyboard.press('Shift+Tab')
    await expect(back).toBeFocused()
    await expect(back).toHaveCSS('outline-style', 'solid')
    await page.screenshot({ path: testInfo.outputPath('github-import.png') })
    await page.keyboard.press('Enter')
    await expect(page).toHaveURL('/new')
    await expect(page.getByRole('button', { name: '刷新资料' })).toBeVisible()
  })
}

test('mobile project navigation reaches sync and switches back after creating a project', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const mobileNavigation = page.getByRole('navigation', { name: '移动端项目导航' })
  const assertShell = async (hasRefresh = true) => {
    await expect(page.locator('.app-topbar')).toBeVisible()
    await expect(mobileNavigation).toBeVisible()
    await expect(page.getByRole('navigation', { name: '项目导航', exact: true })).toBeHidden()
    if (hasRefresh) {
      await expect(page.getByRole('button', { name: '刷新资料' })).toBeVisible()
    } else {
      await expect(page.getByRole('button', { name: '刷新资料' })).toHaveCount(0)
    }
    expect(await page.locator('html').evaluate((element) => element.scrollWidth)).toBeLessThanOrEqual(390)
  }
  await assertShell()
  await mobileNavigation.getByRole('link', { name: '项目', exact: true }).click()
  await expect(page).toHaveURL('/project/project-demo-family/manage/overview')
  await assertShell(false)
  await page.screenshot({ path: testInfo.outputPath('mobile-project-overview.png') })
  const sync = page.getByRole('link', { name: '打开协作同步' })
  await sync.focus()
  await expect(sync).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL('/project/project-demo-family/collaboration-sync')
  await expect(page.getByRole('heading', { name: '协作同步', exact: true })).toBeVisible()
  await assertShell()

  await mobileNavigation.getByRole('link', { name: '项目', exact: true }).click()
  await page.getByRole('link', { name: '打开项目设置' }).click()
  await assertShell()
  await mobileNavigation.getByRole('link', { name: '项目', exact: true }).click()
  await page.locator('.project-overview').getByRole('link', { name: '新建项目', exact: true }).click()
  await expect(page).toHaveURL('/project/project-demo-family/manage/new')
  await expect(page.getByRole('button', { name: '刷新资料' })).toHaveCount(0)
  await expect(mobileNavigation).toBeVisible()
  expect(await page.locator('html').evaluate((element) => element.scrollWidth)).toBeLessThanOrEqual(390)
  const back = page.locator('.app-topbar').getByRole('link', { name: '返回项目管理' })
  await back.focus()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Shift+Tab')
  await expect(back).toBeFocused()
  await expect(back).toHaveCSS('outline-style', 'solid')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL('/project/project-demo-family/manage/overview')
  await assertShell(false)

  await page.locator('.project-overview').getByRole('link', { name: '新建项目', exact: true }).click()
  await page.getByLabel('项目名称').fill('移动端第二份家谱')
  await page.screenshot({ path: testInfo.outputPath('mobile-new-project.png') })
  await page.getByRole('button', { name: '建立家谱' }).click()
  await expect(page).toHaveURL(/\/project\/(?!project-demo-family)[^/]+\/tree$/)
  await assertShell()

  await mobileNavigation.getByRole('link', { name: '项目', exact: true }).click()
  await assertShell(false)
  const switcher = page.locator('.project-switcher')
  await switcher.locator('summary').focus()
  await page.keyboard.press('Enter')
  const projects = switcher.getByRole('navigation', { name: '可切换的项目' })
  await expect(projects.getByRole('link', { name: '打开项目：移动端第二份家谱' })).toBeVisible()
  const original = projects.getByRole('link').filter({ hasNotText: '移动端第二份家谱' }).first()
  await original.focus()
  await expect(original).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('mobile-project-switcher.png') })
  await page.keyboard.press('Escape')
  await expect(switcher.locator('summary')).toBeFocused()
  await expect(projects).toBeHidden()
  await page.keyboard.press('Enter')
  await original.click()
  await expect(page).toHaveURL(/\/project\/project-demo-family\/tree(?:\?|$)/)
  await assertShell()
})
