import { expect, test } from '@playwright/test'
import { expectNoRuntimeErrors, openDemo, resetDemo, watchRuntimeErrors } from './helpers/demo'

test.beforeEach(async ({ page }) => resetDemo(page))

test('exact-name matches come first in tree search and the people list', async ({ page }) => {
  const errors = watchRuntimeErrors(page)
  const treeSearch = page.getByRole('searchbox', { name: '搜索跳转人物' })
  await treeSearch.fill('赵雯')
  const results = page.getByRole('region', { name: '人物搜索结果' })
  await expect(results).toContainText('找到 2 位人物')
  await expect(results.getByRole('button').first()).toHaveAttribute('aria-label', '定位赵雯')
  await treeSearch.press('Enter')
  await expect(page.locator('.family-graph').getByRole('status')).toHaveText('赵雯对其他人物的称呼')

  await openDemo(page, '/people')
  const peopleSearch = page.getByRole('searchbox', { name: '搜索人物', exact: true })
  await peopleSearch.fill('赵雯')
  await expect(page.locator('[data-person-name]')).toHaveText(['赵雯', '林晨'])
  await expect(page.getByRole('option', { name: '按匹配程度' })).toBeAttached()
  await page.reload()
  await expect(page.locator('[data-person-name]')).toHaveText(['赵雯', '林晨'])
  await peopleSearch.fill('')
  await expect(page.locator('[data-person-name]').first()).toHaveText('陈芳')
  await expect(page.getByRole('option', { name: '按姓名', exact: true })).toBeAttached()
  expectNoRuntimeErrors(errors)
})

for (const width of [1440, 900]) {
  test(`partial-name search locates a person without a floating directory at ${width}px`, async ({ page }, testInfo) => {
    const errors = watchRuntimeErrors(page)
    await page.setViewportSize({ width, height: 1000 })
    const search = page.getByRole('searchbox', { name: '搜索跳转人物' })
    await search.fill('梅兰')
    const results = page.getByRole('region', { name: '人物搜索结果' })
    await expect(results).toContainText('找到 1 位人物')
    await expect(results.getByRole('button', { name: '定位王梅兰' })).toBeVisible()
    await search.press('ArrowDown')
    await expect(results.getByRole('button', { name: '定位王梅兰' })).toBeFocused()
    await page.keyboard.press('Enter')
    const selectionStatus = page.locator('.family-graph').getByRole('status')
    await expect(selectionStatus).toHaveText('王梅兰对其他人物的称呼')
    await expect(page.getByRole('complementary', { name: '为王梅兰添加关系' })).toHaveCount(0)
    await expect(page.getByTestId('family-graph').locator('canvas').first()).toBeVisible()
    await expect(page.locator('.family-graph details')).toHaveCount(0)
    await expect(page.locator('.family-graph button')).toHaveCount(0)
    await expect(page.locator('.app-topbar')).toBeVisible()
    expect(await page.locator('html').evaluate((element) => element.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: testInfo.outputPath('search-and-kinship.png') })

    await search.fill('')
    await expect(selectionStatus).toHaveText('王梅兰对其他人物的称呼')
    await expect(results).toHaveCount(0)
    await search.fill('查无此人的测试关键词')
    await expect(results).toContainText('未找到匹配人物')
    expectNoRuntimeErrors(errors)
  })
}

test('keyboard search switches the selected person and Escape clears the perspective', async ({ page }, testInfo) => {
  const errors = watchRuntimeErrors(page)
  await page.setViewportSize({ width: 1440, height: 1000 })
  const search = page.getByRole('searchbox', { name: '搜索跳转人物' })
  const selectionStatus = page.locator('.family-graph').getByRole('status')
  await search.fill('晨晨')
  await expect(page.getByRole('button', { name: '定位林晨', exact: true })).toBeVisible()
  await search.press('Enter')
  await expect(selectionStatus).toHaveText('林晨对其他人物的称呼')
  await expect(page.getByRole('region', { name: '研究视图：林晨的家庭关系' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('everyday-kinship.png') })
  await search.fill('林海')
  await expect(page.getByRole('button', { name: '定位林海', exact: true })).toBeVisible()
  await search.press('Enter')
  await expect(selectionStatus).toHaveText('林海对其他人物的称呼')
  const preview = page.getByRole('region', { name: '研究视图：林海的家庭关系' })
  await expect(preview).toBeVisible()
  await preview.getByRole('button', { name: '关闭人物预览' }).focus()
  await page.keyboard.press('Escape')
  await expect(selectionStatus).toHaveCount(0)
  await expect(preview).toHaveCount(0)
  expectNoRuntimeErrors(errors)
})
