import { expect, test } from '@playwright/test'
import { DEMO_PROJECT_PATH, expectNoRuntimeErrors, resetDemo, watchRuntimeErrors } from './helpers/demo'

test.beforeEach(async ({ page }) => resetDemo(page))

test('adding a child from the mother immediately connects both chosen parents and survives reload', async ({ page }, testInfo) => {
  const errors = watchRuntimeErrors(page)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`${DEMO_PROJECT_PATH}/tree?previewPersonId=person-chen-fang`)
  await page.getByRole('button', { name: '为陈芳添加子女', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '为陈芳添加子女', exact: true })
  await dialog.getByRole('textbox', { name: '姓名', exact: true }).fill('双亲连线子女')
  await dialog.getByRole('combobox', { name: '关系性质', exact: true }).selectOption('biological')
  await expect(dialog.getByRole('combobox', { name: '另一位家长', exact: true })).toHaveValue('')
  await dialog.getByRole('button', { name: '添加并关联', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('请选择另一位家长')
  await dialog.getByRole('combobox', { name: '另一位家长', exact: true }).selectOption('person-lin-hai')
  await dialog.getByRole('combobox', { name: '另一位家长与孩子的关系', exact: true }).selectOption('biological')
  await dialog.getByRole('button', { name: '添加并关联', exact: true }).click()
  await expect(dialog).toBeHidden()

  const search = page.getByRole('searchbox', { name: '搜索跳转人物' })
  await search.fill('双亲连线子女')
  await expect(page.getByRole('button', { name: '定位双亲连线子女', exact: true })).toBeVisible()
  await search.press('Enter')
  const preview = page.getByRole('region', { name: '研究视图：双亲连线子女的家庭关系', exact: true })
  await expect(preview).toContainText('亲生父亲')
  await expect(preview).toContainText('林海')
  await expect(preview).toContainText('亲生母亲')
  await expect(preview).toContainText('陈芳')
  await expect(page.getByTestId('family-graph').locator('canvas').first()).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('both-parent-links.png') })
  await preview.getByRole('link', { name: '查看人物详情：双亲连线子女', exact: true }).click()
  const relationships = page.locator('[data-person-relationships]')
  await expect(relationships.locator('li[data-relationship-id]')).toHaveCount(2)
  await page.reload()
  await expect(relationships).toContainText('亲生父亲')
  await expect(relationships).toContainText('亲生母亲')
  expectNoRuntimeErrors(errors)
})

test('a single-parent child can explicitly receive the missing father and reconnect both parents', async ({ page }) => {
  const errors = watchRuntimeErrors(page)
  await page.goto(`${DEMO_PROJECT_PATH}/tree?previewPersonId=person-chen-fang`)
  await page.getByRole('button', { name: '为陈芳添加子女', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '为陈芳添加子女', exact: true })
  await dialog.getByRole('textbox', { name: '姓名', exact: true }).fill('仅关联母亲子女')
  await dialog.getByRole('combobox', { name: '关系性质', exact: true }).selectOption('biological')
  await dialog.getByRole('combobox', { name: '另一位家长', exact: true }).selectOption({ label: '仅关联当前家长' })
  await dialog.getByRole('button', { name: '添加并关联', exact: true }).click()
  await expect(dialog).toBeHidden()
  const search = page.getByRole('searchbox', { name: '搜索跳转人物' })
  await search.fill('仅关联母亲子女')
  await expect(page.getByRole('button', { name: '定位仅关联母亲子女', exact: true })).toBeVisible()
  await search.press('Enter')
  const childLink = page.getByRole('link', { name: '查看人物详情：仅关联母亲子女', exact: true })
  const childId = new URL((await childLink.getAttribute('href'))!, page.url()).pathname.split('/').at(-1)!
  await childLink.click()
  const relationships = page.locator('[data-person-relationships]')
  await expect(relationships.locator('li[data-relationship-id]')).toHaveCount(1)
  await expect(relationships).toContainText('亲生母亲')
  await relationships.getByRole('button', { name: '添加已有关系', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '添加人物关系', exact: true })
  await editor.getByRole('combobox', { name: '关联人物', exact: true }).selectOption('person-lin-hai')
  await editor.getByRole('combobox', { name: '关系性质', exact: true }).selectOption('biological')
  await editor.getByRole('combobox', { name: '关系方向', exact: true }).selectOption('relative-is-parent')
  await editor.getByRole('button', { name: '保存关系', exact: true }).click()
  await expect(editor).toBeHidden()
  await expect(relationships.locator('li[data-relationship-id]')).toHaveCount(2)
  await expect(relationships).toContainText('亲生父亲')
  await page.goto(`${DEMO_PROJECT_PATH}/tree?personId=${childId}&previewPersonId=${childId}`)
  const preview = page.getByRole('region', { name: '研究视图：仅关联母亲子女的家庭关系', exact: true })
  await expect(preview).toContainText('亲生父亲')
  await expect(preview).toContainText('亲生母亲')
  expectNoRuntimeErrors(errors)
})

test('the narrow-screen workflow records both parents and shows them in the child branch', async ({ page }, testInfo) => {
  const errors = watchRuntimeErrors(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`${DEMO_PROJECT_PATH}/people/person-chen-fang`)
  await page.locator('[data-person-relationships]').getByRole('button', { name: '添加人物', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '添加人物与关系', exact: true })
  await dialog.getByRole('textbox', { name: '姓名', exact: true }).fill('手机双亲子女')
  await dialog.getByRole('combobox', { name: '关系性质', exact: true }).selectOption('biological')
  await dialog.getByRole('combobox', { name: '关系方向', exact: true }).selectOption('current-is-parent')
  await dialog.getByRole('combobox', { name: '另一位家长', exact: true }).selectOption('person-lin-hai')
  await dialog.getByRole('combobox', { name: '另一位家长与孩子的关系', exact: true }).selectOption('biological')
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('narrow-parent-selection.png') })
  await dialog.getByRole('button', { name: '添加并关联', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.goto(`${DEMO_PROJECT_PATH}/people`)
  await page.getByRole('searchbox', { name: '搜索人物', exact: true }).fill('手机双亲子女')
  const childLink = page.getByRole('link', { name: '打开人物详情：手机双亲子女', exact: true })
  await expect(childLink).toBeVisible()
  const childId = (await childLink.getAttribute('href'))!.split('/').at(-1)!
  await page.goto(`${DEMO_PROJECT_PATH}/tree?personId=${childId}`)
  const parents = page.locator('[data-branch="parents"]')
  await expect(parents).toContainText('林海')
  await expect(parents).toContainText('陈芳')
  await expect(parents.getByRole('button', { name: /为.*添加父母/ })).toBeVisible()
  expect(await page.locator('html').evaluate((element) => element.scrollWidth)).toBeLessThanOrEqual(390)
  await page.reload()
  await expect(parents).toContainText('林海')
  await expect(parents).toContainText('陈芳')
  expectNoRuntimeErrors(errors)
})
